---
title: "Théo4-Nouvel Excel"
author: "Christoph"
date: "2023-10-05,10"
output:
  pdf_document:
    latex_engine: xelatex
    toc: no
    toc_depth: 3
    extra_dependencies: []
    keep_tex: yes
  word_document:
    toc: no
    toc_depth: '3'
geometry: margin=0.5cm
---


# Libraries

```{r, comment=FALSE, warning=FALSE, message=FALSE}
library(xlsx)                                         # Fichiers Excel
library(jmv)                                          # Analyses Jamovi
library(dplyr)                                        # filter etc.
#library(tigerstats)                                   # beaux tableaux croisés
```


# Données

## Lire

```{r}
setwd("/Users/christophpahl/Bureau/Travail+Hobby/Statistiques/Théo")
TOUT <- read.xlsx("MA_Theo_tableau1-ed.xlsx", sheetName ="Feuil1") 
```


## Afficher

(sur écran mais pas dans le PDF ou word)

```{r}
View(TOUT)
#noquote(colnames(TOUT))   # Noms des Variables j'ai un fichier Théo-Nouv-Colnames.txt
```

dernier = [654] Neg_parent_humiliation_3cat_3 = Excel


# MPS

```{r}
avait <- function(item){
  return( ifelse(item != "Jamais" & item != "0",1,0) )   # "0" occure seulement pour TOUT$mpsy_parent_invesstissment_item2 
}
```

```{r}
TOUT$mps <- avait(TOUT$Mphysique_pairs_item1)                 + avait(TOUT$Mphysique_paire_item2)         +
            avait(TOUT$Mphysique_paire_item3)     +

            avait(TOUT$Mphysique_adulte_secoue_agrippe_item1) + avait(TOUT$Mphysique_adulte_frappe_item2) + 
            avait(TOUT$Mphysique_adulte_etouffe_item3)    +
  
            avait(TOUT$Mphysique_parent_secoue)               + avait(TOUT$Mphysique_parent_frappe)       + 
            avait(TOUT$Mphysique_parent_ettoufe)

TOUT$MPS <- if_else(TOUT$mps>0, 1, 0)

MPS <- filter(TOUT, MPS==1)
```

Au total: 344 des 781 participants ont subi au moins une MPS.

```{r}
tableau_auteurs <- function(vec){
  pairs               <- c(round(vec[1],0),round(vec[1]/711,3)*100)
  parents             <- c(round(vec[2],0),round(vec[2]/711,3)*100)
  entraineur          <- c(round(vec[3],0),round(vec[3]/711,3)*100)
  entraineurassistant <- c(round(vec[4],0),round(vec[4]/711,3)*100)
  prepaphysique       <- c(round(vec[5],0),round(vec[5]/711,3)*100)
  medecin             <- c(round(vec[6],0),round(vec[6]/711,3)*100)
  arbitre             <- c(round(vec[7],0),round(vec[7]/711,3)*100)
  psychologe          <- c(round(vec[8],0),round(vec[8]/711,3)*100)
  adulte_autre        <- c(round(vec[9],0),round(vec[9]/711,3)*100)

  df <- data.frame(pairs, parents, entraineur, entraineurassistant, prepaphysique, medecin, arbitre, psychologe, adulte_autre)
  rownames(df) <- c("nombre","pourcentage")
  df
}
```


## Recoder

```{r}
# grep -i mphys Théo4-Nouv-Colnames.txt |grep -i pair|grep -i item :
MPS$auteur_pair  <- avait(MPS$Mphysique_pairs_item1) + avait(MPS$Mphysique_paire_item2) + avait(MPS$Mphysique_paire_item3) > 0   # = nouveau XL

# grep -i mphys Théo4-Nouv-Colnames.txt |grep -i parent :
MPS$auteur_parents <- avait(MPS$Mphysique_parent_secoue) + avait(MPS$Mphysique_parent_frappe) + avait(MPS$Mphysique_parent_ettoufe) > 0   # = nouveau XL

vec <- c(
  sum(MPS$auteur_pair   > 0),

  sum(MPS$auteur_parents > 0),

  # grep -i mphys Théo4-Nouv-Colnames.txt |grep -i adulte|grep -i auteur :

  sum((MPS$Mphysique_adulte_auteur_entraineur== "Oui") > 0) ,
  sum((MPS$Mphysique_adulte_auteur_entraineurassistant== "Oui") > 0) ,
  sum((MPS$Mphysique_adulte_auteur_prepaphysique== "Oui") > 0) ,
  sum((MPS$Mphysique_adulte_auteur_medecin== "Oui") > 0) ,
  sum((MPS$Mphysique_adulte_auteur_arbitre== "Oui") > 0) ,
  sum((MPS$Mphysique_adulte_auteur_psy== "Oui") > 0) ,
  sum((MPS$Mphysique_adulte_auteur_autre== "Oui") > 0) )

tableau_auteurs(vec)
```
  
----------------------------------------------------------------------------

# PSY

```{r}
TOUT$psy <- avait(TOUT$Mpsy_paire_ignoré_item1) + avait(TOUT$Mpsy_paire_investissement_item2) +   # ~ nouvel Exel
            avait(TOUT$Mpsy_paire_critique_perf_item3) + avait(TOUT$Mpsy_paire_apparence_item4) +
            avait(TOUT$Mpsy_paire_rumeur_item5) + avait(TOUT$Mpsy_paire_humiliation_item6) +
            avait(TOUT$Mpsy_paire_menace_exclusion_item7) + avait(TOUT$mpsy_paire_menace_physique_item8) +
            avait(TOUT$Mpsy_paire_encourager_humiliation_item9) + avait(TOUT$mpsy_paire_limite_contacte_item10) +

            avait(TOUT$Mpsy_adulte_ignoer_item1) + avait(TOUT$mpsy_adulte_critique_invesstissement_item2) +   # ~ nouvel Exel
            avait(TOUT$mpsy_adulte_critique_perf_item2) + avait(TOUT$mpsy_adulte_critiquer_apparence_item3) +
            avait(TOUT$mpsy_adulte_rumeur_item4) + avait(TOUT$mpsy_adulte_ridiculiser_item5) +
            avait(TOUT$Mpsy_adulte_crier_dessus_item6) + avait(TOUT$mpsy_adulte_menace_expulsion_item7) +
            avait(TOUT$mpsy_adulte_menacephysi_item8) + avait(TOUT$mpsy_adulte_humiliation_autrui_item9) +
            avait(TOUT$mpsy_adulte_limitation_contact_item10) + avait(TOUT$mpsy_adulte_jouer_blesser_item11) +
            avait(TOUT$mpsy_adulte_entrainer_a_vomir_item12) + avait(TOUT$mpsy_adulte_dopage_item13) +
            avait(TOUT$mpsy_adulte_poids_ideal_item13) +

            avait(TOUT$Mpsy_parent_ignorer_item1) + avait(TOUT$mpsy_parent_invesstissment_item2) +   # ~ nouvel Exel
            # item2 pas encodé comme les autres
            avait(TOUT$mpsy_parent_critique_perf_item3) +
  avait(TOUT$Mpsy_parent_critique_corps_item4) +
            avait(TOUT$mpsy_parent_rumeur_item5) + avait(TOUT$mpsy_parent_ridiculisà_perf_item6) +
  
            avait(TOUT$mpsy_parent_crier_dessus_item7) + avait(TOUT$Mpsy_parent_menace_physique_item8) + 
            avait(TOUT$Mpsy_parent_blesser_adversaire_item9) + avait(TOUT$Mpsy_parent_limite_contact_item10) + 
            avait(TOUT$Mpsy_parent_blessé_soi_mm_item11) + avait(TOUT$mpsy_parent_vomir_item12) + 
            avait(TOUT$mpsy_parent_dopage_item13) + avait(TOUT$Mpsy_parent_poids_ideal_item14)
  
TOUT$PSY <- if_else(TOUT$psy > 0, 1, 0)
PSY <- filter(TOUT, PSY==1)
```

711 ont subi au moins une maltraitance psychologique 
`

## Recoder


```{r}
# grep -i psy Théo4-Nouv-Colnames.txt |grep -i paire|grep -i item :
PSY$auteur_pairs   <- avait(PSY$Mpsy_paire_ignoré_item1)+ avait(PSY$Mpsy_paire_investissement_item2)+
                      avait(PSY$Mpsy_paire_critique_perf_item3)+ avait(PSY$Mpsy_paire_apparence_item4)+
                      avait(PSY$Mpsy_paire_rumeur_item5)+ avait(PSY$Mpsy_paire_humiliation_item6)+
                      avait(PSY$Mpsy_paire_menace_exclusion_item7)+ avait(PSY$mpsy_paire_menace_physique_item8)+
                      avait(PSY$Mpsy_paire_encourager_humiliation_item9)+ avait(PSY$mpsy_paire_limite_contacte_item10) 

# grep -i psy Théo4-Nouv-Colnames.txt |grep  -i adulte|grep -i item :
PSY$auteur_adulte  <- avait(PSY$Mpsy_adulte_ignoer_item1)+ avait(PSY$mpsy_adulte_critique_invesstissement_item2)+
                      avait(PSY$mpsy_adulte_critique_perf_item2)+ avait(PSY$mpsy_adulte_critiquer_apparence_item3)+
                      avait(PSY$mpsy_adulte_rumeur_item4)+ avait(PSY$mpsy_adulte_ridiculiser_item5)+
                      avait(PSY$Mpsy_adulte_crier_dessus_item6)+ avait(PSY$mpsy_adulte_menace_expulsion_item7)+
                      avait(PSY$mpsy_adulte_menacephysi_item8)+ avait(PSY$mpsy_adulte_humiliation_autrui_item9)+
                      avait(PSY$mpsy_adulte_limitation_contact_item10)+ avait(PSY$mpsy_adulte_jouer_blesser_item11)+
                      avait(PSY$mpsy_adulte_entrainer_a_vomir_item12)+ avait(PSY$mpsy_adulte_dopage_item13)+
                      avait(PSY$mpsy_adulte_poids_ideal_item13) 

# grep -i psy Théo4-Nouv-Colnames.txt |grep -i parent|grep -i item :
PSY$auteur_parents <- avait(PSY$Mpsy_parent_ignorer_item1)+ avait(PSY$mpsy_parent_invesstissment_item2)+
                      avait(PSY$mpsy_parent_critique_perf_item3)+ avait(PSY$Mpsy_parent_critique_corps_item4)+
                      avait(PSY$mpsy_parent_rumeur_item5)+ avait(PSY$mpsy_parent_ridiculisà_perf_item6)+
                      avait(PSY$mpsy_parent_crier_dessus_item7)+ avait(PSY$Mpsy_parent_menace_physique_item8)+ 
                      avait(PSY$Mpsy_parent_blesser_adversaire_item9)+ avait(PSY$Mpsy_parent_limite_contact_item10)+ 
                      avait(PSY$Mpsy_parent_blessé_soi_mm_item11)+ avait(PSY$mpsy_parent_vomir_item12)+ 
                      avait(PSY$mpsy_parent_dopage_item13)+ avait(PSY$Mpsy_parent_poids_ideal_item14) 
```

```{r}
vec <- c(
sum(PSY$auteur_pairs   > 0),

sum(PSY$auteur_parents > 0),

# grep -i psy Théo4-Nouv-Colnames.txt |grep -i adulte|grep -i auteur :

sum((PSY$mpsy_adulte_auteur_entraineur  == "Oui") +
    (PSY$Mpsy_adulte_auteur_2_entraineur== "Oui") +
    (PSY$mpsy_adulte_auteur_entraineur.1== "Oui") +
    (PSY$mpsy_adulte_auteur_entraineur_2== "Oui") > 0) ,

sum((PSY$mpsy_adulte_auteur_entraineurassistant == "Oui") +
    (PSY$mpsy_adulte_auteur_entraineur_assistant== "Oui") +
    (PSY$mpsy_adulte_auteur_assist_coach        == "Oui") > 0),

sum((PSY$mpsy_adulte_auteur_prepaphysique == "Oui")+
    (PSY$mpsy_adulte_auteur_prepa_physique== "Oui") +
    (PSY$mpsy_adulte_auteur_prepaphy      == "Oui") +
    (PSY$mpsy_adulte_auteur_prepaphy_2    == "Oui") > 0),

sum((PSY$mpsy_adulte_auteur_medecin  == "Oui") +
    (PSY$mpsy_adulte_auteur_medecin.1== "Oui") > 0),
  
sum((PSY$mpsy_adulte_auteur_arbitre  == "Oui") +
    (PSY$mpsy_adulte_auteur_arbitre.1== "Oui") +
    (PSY$mpsy_adulte_auteur_arbitre_2== "Oui") +
    (PSY$mpsy_adulte_auteur_arbitre_3== "Oui") > 0),
  
sum((PSY$mpsy_adulte_auteur_psychologue== "Oui") +
    (PSY$Mpsy_adulte_auteur_psychologue== "Oui") +
    (PSY$mpsy_adulte_auteur_psy        == "Oui") > 0),
  
sum((PSY$mpsy_adulte_auteur_autre  == "Oui") +
    (PSY$mpsy_adulte_auteur_autre.1== "Oui") +
    (PSY$mpsy_adulte_auteur_autre_2== "Oui") +
    (PSY$mpsy_adulte_auteur_autre_3== "Oui") > 0))

#TRUE                                              ~ "ne pas specifié"   ))   müsste sum=0 zählen. lohnt noicht!
```

Le maltraitances psychologiques étaient commis par un ou plusieurs auteurs (à partir des données on ne peut pas differencier leur nombre), avec le nombre de cas ou pourcentage sur les 711 cas PSY comme detaillé dans le tableau suivant:

```{r}
tableau_auteurs(vec)
```


# NEG

```{r}
TOUT$neg <- avait(TOUT$negadulte_item._cat_1) + avait(TOUT$negadulte_item2_cat_1) +
            avait(TOUT$negadulte_item_3_cat_1) > avait(TOUT$Neg_adulte_louper_ecole_item4) +
            avait(TOUT$Neg_adulte_laisser_humilier_item5) +

            avait(TOUT$Neg_parent_laisser_entrainer_blesser_item1) + avait(TOUT$Neg_parent_dopage_item2) +
            avait(TOUT$Neg_parent_poids_ideal_item3) +              avait(TOUT$Neg_parent_arret_ecole_item4) +
            avait(TOUT$neg_parent_laisser_humilier_autrui_item5) 

TOUT$NEG <- if_else(TOUT$neg > 0, 1, 0)

NEG <- filter(TOUT, NEG==1)
```

117 ont subi NEG.
 
## Recoder

```{r}
# grep -i neg Théo4-Nouv-Colnames.txt |grep -i parent|grep -i item :
NEG$auteur_parents <- avait(NEG$Neg_parent_laisser_entrainer_blesser_item1) + avait(NEG$Neg_parent_dopage_item2) +
                      avait(NEG$Neg_parent_poids_ideal_item3) + avait(NEG$Neg_parent_arret_ecole_item4) +
                      avait(NEG$neg_parent_laisser_humilier_autrui_item5)

# grep -i neg Théo4-Nouv-Colnames.txt |grep -i adult  :                  
vec <- c(
  0,
  sum(NEG$auteur_parents > 0),
                      
  sum((NEG$Neg_adulte_entraineur_cat_1== "Oui") +
      (NEG$Neg_adulte_entraineur      == "Oui") +
      (NEG$Neg_adulte_entraineur_2    == "Oui") > 0) ,
                     
  sum((NEG$Neg_adulte_assit_entrain_cat_1== "Oui") +
      (NEG$Neg_adulte_entraineur_assit== "Oui") +
      (NEG$Neg_adulte_entraineur_assistant== "Oui") > 0) ,

  sum((NEG$Neg_adulte_prepa_physiqu_cat_1== "Oui") +
      (NEG$neg_adulte_prepa_physique== "Oui") +
      (NEG$Neg_adulte_prepa_phys== "Oui") > 0) ,

  sum((NEG$Neg_adulte_medecin_cat_1== "Oui") +
      (NEG$Neg_adulte_medecin_2== "Oui") +
      (NEG$Neg_adulte_medecin_3== "Oui") > 0) ,

  sum((NEG$Neg_adulte_arbitre_cat_1== "Oui") +
      (NEG$neg_adulte_arbitre== "Oui") +
      (NEG$Neg_adulte_arbitrw== "Oui") > 0) ,

  sum((NEG$Neg_adulte_Psy_cat_1== "Oui") +
      (NEG$neg_adulte_psy_2== "Oui") +
      (NEG$neg_adulte_psy_3== "Oui") > 0) ,

  sum((NEG$Neg_adulte_autre_cat_1== "Oui") +
      (NEG$neg_adulte_autre== "Oui") +
      (NEG$Neg_adulte_autre== "Oui") > 0))
      
tableau_auteurs(vec)                
```

J'ai bien contrôlé: il n'y a pas de négligance par arbitre ou psychologe.

----------------------------------------------------------------------------------

# SEX

```{r}
TOUT$sex <- avait(TOUT$Msex_paire_remarque_apparence_item1)    + avait(TOUT$Msex_paire_proposition_sex_item2)  +
            avait(TOUT$msex_paire_exhibitionisme_item3)        + avait(TOUT$msex_paire_photo_intime_item4)     +
            avait(TOUT$msex_paire_attouchement_item5)          + avait(TOUT$Msex_paire_embrasser_item6)        +
            avait(TOUT$msex_paire_frotter_partie_intime_item7) + avait(TOUT$msex_paire_viol_penetration_item7) +
            avait(TOUT$Msex_paire_avec_sans_penetration_non_consentie_item8)    +

            avait(TOUT$Msex_adulte_remarque_sex_item1)             + avait(TOUT$msex_adulte_envoi_image_sex_item2)       +
            avait(TOUT$Msex_adulte_exhibition_partie_intime_item_3_categorie_2) +        # = Excel
            #          Msex_adulte_exhibition_partie_intime_item2...item_3_categorie_2.. # = .txt, egal
            avait(TOUT$msex_adulte_photo_partie_intime_item_4_categorie_3) +
            avait(TOUT$msex_adulte_force.a_toucher_item_5_categorie_4)          +                                                      
            avait(TOUT$msex_adulte_toucher_malalaise_Item6_categorie_5)     +
            avait(TOUT$msex_adulte_embrasser_bouche_Item_7_categorie_5)         +            
            avait(TOUT$Msex_adulte_frotter_partie_intime_item_8_categorie_5) +
            avait(TOUT$Msex_adulte_tentation_relation_sex_item_9_categorie_6)   + 
            avait(TOUT$Msex_adulte_forcer_relation_sex_avec_sans_pene_item8) 
  
TOUT$SEX <- if_else(TOUT$sex > 0, 1, 0)

SEX <- filter(TOUT, SEX==1)
```

178 ont subi SEX.

 
## Recoder

# grep -i msex Théo4-Nouv-Colnames.txt |grep -i paire|grep -i item :
```{r}
SEX$auteur_paire   <-avait(SEX$Msex_paire_remarque_apparence_item1)   +avait(SEX$Msex_paire_proposition_sex_item2) +
                     avait(SEX$msex_paire_exhibitionisme_item3)       +avait(SEX$msex_paire_photo_intime_item4)    +
                     avait(SEX$msex_paire_attouchement_item5)         +avait(SEX$Msex_paire_embrasser_item6)       +
                     avait(SEX$msex_paire_frotter_partie_intime_item7)+avait(SEX$msex_paire_viol_penetration_item7)+
                     avait(SEX$Msex_paire_avec_sans_penetration_non_consentie_item8)  
```

```{r}
vec <- c(
  sum(SEX$auteur_paire   > 0),
  0,

# grep -i msex Théo4-Nouv-Colnames.txt |grep -i adult|grep -i auteur  :

  sum((SEX$mpsy_adulte_auteur_entraineur  == "Oui") +
      (SEX$Msex_adulte_auteur_entraineur  == "Oui") +
      (SEX$Msex_adulte_auteur_entraineur_2  == "Oui") +
      (SEX$Msex_adulte_auteur_entraineur_2_categorie_6  == "Oui") +
      (SEX$Msex_adulte_auteur_entraineur_2_categorie_7  == "Oui") > 0),

  sum((SEX$msex_adulte_auteur_entraineur_assis_2_categorie_6  == "Oui") +
      (SEX$msex_adulte_auteur_entraineur_assis_2_categorie_7  == "Oui"),
      (SEX$msex_adulte_auteur_entraineur_assis_2  == "Oui"),
      (SEX$msex_adulte_auteur_entraineur_assis  == "Oui") > 0),

  sum((SEX$msex_adulte_auteur_prepa_physique  == "Oui") > 0),

  sum((SEX$Msex_adulte_auteur_medecin  == "Oui") +
      (SEX$msex_adulte_auteur_medecin  == "Oui"),
      (SEX$msex_adulte_auteur_medecin_categorie_6  == "Oui"),
      (SEX$msex_adulte_auteur_medecin_categorie_7  == "Oui") > 0),

  sum((SEX$msex_adulte_auteur_arbitre  == "Oui"),
      (SEX$msex_adulte_auteur_arbitre_2  == "Oui"),
      (SEX$msex_adulte_auteur_arbitre_2_categorie_6  == "Oui"),
      (SEX$msex_adulte_auteur_arbitre_2_categorie_7  == "Oui") > 0),

  sum((SEX$msex_adulte_auteur_psy  == "Oui"),
      (SEX$msex_adulte_auteur_psy_2_categorie_6  == "Oui"),
      (SEX$msex_adulte_auteur_psy_2  == "Oui"),
      (SEX$msex_adulte_auteur_psy_2_categorie_7  == "Oui") > 0),

  sum((SEX$msex_adulte_auteur_autre_2_categorie_7  == "Oui"),
      (SEX$msex_adulte_auteur_autre_2_categorie_6  == "Oui"),
      (SEX$msex_adulte_auteur_autre  == "Oui"),
      (SEX$msex_adulte_auteur_autre_2  == "Oui") > 0) )

tableau_auteurs(vec)
```

J'ai bien contrôlé: il n'ya pas de m altraitance sexuelle par un psychologue.
